[package]
name = "concat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.23", features = ["derive"]}
anyhow = "1.0.95"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
pretty_assertions = "1.4.1"